// Where the "Download CV" buttons point.
//
// The files are generated by `npm run build:cv` from scripts/cv-data.cjs and
// checked by `npm run verify:cv`. The filenames carry the name and the role on
// purpose: in a recruiter's folder of 200 PDFs, the filename is metadata.

export const CV_HREF = {
  en: '/Emiliano-Garcia-Fuenzalida-UX-UI-Designer-CV-EN.pdf',
  es: '/Emiliano-Garcia-Fuenzalida-Disenador-UX-UI-CV-ES.pdf',
} as const;
